import { uid } from './utils.js';

export const THEME_PRESETS = {
  lavenderDream: {
    name: 'Lavender Dream',
    swatch: 'linear-gradient(135deg, #c4a0ff, #e8b4f8, #f0a8d0)',
    vars: {
      '--bg-primary': '#0c0818',
      '--bg-secondary': '#14102a',
      '--bg-elevated': 'rgba(22, 16, 42, 0.72)',
      '--glass-bg': 'rgba(28, 20, 52, 0.55)',
      '--glass-border': 'rgba(196, 160, 255, 0.22)',
      '--accent-primary': '#c4a0ff',
      '--accent-secondary': '#e8b4f8',
      '--accent-rose': '#f0a8d0',
      '--accent-rose-gold': '#d4a88c',
      '--accent-glow': 'rgba(196, 160, 255, 0.45)',
      '--accent-glow-strong': 'rgba(232, 180, 248, 0.65)',
      '--gradient-heading': 'linear-gradient(135deg, #e8b4f8 0%, #c4a0ff 45%, #f0a8d0 100%)',
      '--gradient-accent': 'linear-gradient(135deg, #9b7bdb 0%, #c4a0ff 50%, #e8b4f8 100%)',
    },
  },
  neonPink: {
    name: 'Neon Pink',
    swatch: 'linear-gradient(135deg, #ff65ff, #ff3d9a, #c44dff)',
    vars: {
      '--bg-primary': '#0a000f',
      '--bg-secondary': '#150018',
      '--bg-elevated': 'rgba(20, 4, 28, 0.75)',
      '--glass-bg': 'rgba(30, 8, 40, 0.55)',
      '--glass-border': 'rgba(255, 101, 255, 0.25)',
      '--accent-primary': '#ff65ff',
      '--accent-secondary': '#ff8fd8',
      '--accent-rose': '#ff3d9a',
      '--accent-rose-gold': '#ffb8d0',
      '--accent-glow': 'rgba(255, 101, 255, 0.5)',
      '--accent-glow-strong': 'rgba(255, 141, 216, 0.7)',
      '--gradient-heading': 'linear-gradient(135deg, #ff8fd8, #ff65ff, #c44dff)',
      '--gradient-accent': 'linear-gradient(135deg, #ff3d9a, #ff65ff, #c44dff)',
    },
  },
  midnightRose: {
    name: 'Midnight Rose',
    swatch: 'linear-gradient(135deg, #2d1b3d, #8b5a7a, #d4a0a8)',
    vars: {
      '--bg-primary': '#0d0812',
      '--bg-secondary': '#1a1020',
      '--bg-elevated': 'rgba(26, 16, 32, 0.75)',
      '--glass-bg': 'rgba(35, 20, 40, 0.55)',
      '--glass-border': 'rgba(212, 160, 168, 0.22)',
      '--accent-primary': '#d4a0a8',
      '--accent-secondary': '#b88a9a',
      '--accent-rose': '#e8b4c0',
      '--accent-rose-gold': '#c9a080',
      '--accent-glow': 'rgba(212, 160, 168, 0.4)',
      '--accent-glow-strong': 'rgba(232, 180, 192, 0.6)',
      '--gradient-heading': 'linear-gradient(135deg, #e8b4c0, #d4a0a8, #c9a080)',
      '--gradient-accent': 'linear-gradient(135deg, #8b5a7a, #d4a0a8, #e8b4c0)',
    },
  },
  cyberLilac: {
    name: 'Cyber Lilac',
    swatch: 'linear-gradient(135deg, #7c3aed, #a78bfa, #22d3ee)',
    vars: {
      '--bg-primary': '#050510',
      '--bg-secondary': '#0c0c20',
      '--bg-elevated': 'rgba(12, 12, 32, 0.8)',
      '--glass-bg': 'rgba(16, 16, 40, 0.6)',
      '--glass-border': 'rgba(167, 139, 250, 0.25)',
      '--accent-primary': '#a78bfa',
      '--accent-secondary': '#c4b5fd',
      '--accent-rose': '#22d3ee',
      '--accent-rose-gold': '#f0abfc',
      '--accent-glow': 'rgba(167, 139, 250, 0.45)',
      '--accent-glow-strong': 'rgba(34, 211, 238, 0.5)',
      '--gradient-heading': 'linear-gradient(135deg, #a78bfa, #c4b5fd, #22d3ee)',
      '--gradient-accent': 'linear-gradient(135deg, #7c3aed, #a78bfa, #22d3ee)',
    },
  },
};

export const BG_ANIMATIONS = [
  'none', 'petals', 'stars', 'aurora', 'bokeh', 'shimmer', 'grid', 'hearts', 'snow',
];

export const SOCIAL_PLATFORMS = {
  discord: { icon: '💬', label: 'Discord' },
  tiktok: { icon: '🎵', label: 'TikTok' },
  youtube: { icon: '▶️', label: 'YouTube' },
  twitter: { icon: '🐦', label: 'Twitter/X' },
  instagram: { icon: '📸', label: 'Instagram' },
  twitch: { icon: '🎮', label: 'Twitch' },
  github: { icon: '💻', label: 'GitHub' },
  link: { icon: '🔗', label: 'Link' },
};

export function detectPlatform(url) {
  const u = (url || '').toLowerCase();
  if (u.includes('discord')) return 'discord';
  if (u.includes('tiktok')) return 'tiktok';
  if (u.includes('youtube') || u.includes('youtu.be')) return 'youtube';
  if (u.includes('twitter') || u.includes('x.com')) return 'twitter';
  if (u.includes('instagram')) return 'instagram';
  if (u.includes('twitch')) return 'twitch';
  if (u.includes('github')) return 'github';
  return 'link';
}

export function createDefaultConfig() {
  return {
    site: {
      title: 'Suki | Creator Hub',
      favicon: '',
      enterScreen: true,
      enterTitle: 'Welcome',
      enterSubtitle: 'sukiii.xyz',
      maintenanceMode: false,
      maintenanceMessage: 'Be right back — sprucing things up! ✨',
      cursor: 'sparkle',
      cursorCustomUrl: '',
      pageTransition: 'fade',
      cardHover: 'lift',
      showMusicPlayer: true,
    },
    theme: {
      preset: 'lavenderDream',
      custom: {},
      overlays: [],
      glowIntensity: 1,
    },
    background: {
      type: 'gradient',
      solid: '#0c0818',
      gradient: 'linear-gradient(180deg, #1a0a2e 0%, #2d1b4e 30%, #4a2c6a 60%, #6b3fa0 100%)',
      image: '',
      video: '',
      animation: 'petals',
      speed: 1,
      opacity: 0.85,
    },
    typography: {
      displayFont: 'Playfair Display',
      bodyFont: 'Quicksand',
      baseSize: 16,
      headingEffect: 'gradient',
      headingWeight: 600,
      bodyWeight: 400,
      letterSpacing: 0.02,
      lineHeight: 1.65,
    },
    profile: {
      displayName: 'NekiraBelle (Suki)',
      username: '@nekirabelle',
      nickname: 'Suki',
      tagline: 'Sweet streamer energy with neon glow ✨',
      bio: '21 // Female // DBD + RE // Nyxia Staff & Content Creator // Discord: zsukiii',
      avatar: '',
      avatarBorder: 'glow',
      avatarHover: 'pulse',
      banner: '',
    },
    socialLinks: [
      { id: uid(), url: 'https://www.tiktok.com/@nekirabelle', platform: 'tiktok', visible: true },
      { id: uid(), url: 'https://discord.gg/nyxia', platform: 'discord', visible: true },
      { id: uid(), url: 'https://www.youtube.com/@nekirabelle', platform: 'youtube', visible: true },
    ],
    badges: [
      {
        id: uid(),
        label: 'Developer',
        icon: '',
        badgeType: 'developer',
        useGradient: true,
        gradientFrom: '#c4a0ff',
        gradientTo: '#f0a8d0',
        textColor: '#ffffff',
        bgColor: 'transparent',
        borderColor: 'transparent',
        tooltip: 'Built this sanctuary from scratch — lavender code witch ✨',
        style: 'glow',
        visible: true,
      },
      {
        id: uid(),
        label: '✨ Suki',
        icon: '✨',
        badgeType: 'custom',
        useGradient: true,
        gradientFrom: '#e8b4f8',
        gradientTo: '#c4a0ff',
        tooltip: 'Your favorite creator — streaming, vibing, and spreading sparkle energy!',
        bgColor: 'rgba(196, 160, 255, 0.18)',
        textColor: '#e8b4f8',
        borderColor: 'rgba(196, 160, 255, 0.4)',
        style: 'glow',
        visible: true,
      },
      {
        id: uid(),
        label: 'Nyxia Staff',
        icon: '🛡️',
        badgeType: 'custom',
        useGradient: false,
        tooltip: 'Official Nyxia team member — here to help you stay ahead of the curve!',
        bgColor: 'rgba(124, 58, 237, 0.18)',
        textColor: '#c4b5fd',
        borderColor: 'rgba(167, 139, 250, 0.4)',
        style: 'gradient',
        visible: true,
      },
      {
        id: uid(),
        label: 'Content Creator',
        icon: '🎬',
        badgeType: 'custom',
        useGradient: false,
        tooltip: 'Creating content across TikTok, YouTube & more — DBD, RE, and beyond!',
        bgColor: 'rgba(240, 168, 208, 0.15)',
        textColor: '#f0a8d0',
        borderColor: 'rgba(240, 168, 208, 0.35)',
        style: 'glow',
        visible: true,
      },
    ],
    navigation: {
      style: 'default',
    },
    tabs: [
      {
        id: uid(),
        label: 'Home',
        type: 'about',
        visible: true,
        content: {
          heading: 'Welcome to my sanctuary',
          subtitle: 'Your cozy corner of the internet — part creator hub, part promo paradise.',
          body: '<p>Hey love! 💜 This is my personal creator hub where you can find everything about me, quick links to my socials, and exclusive promos.</p><p>Expect cozy vibes, gaming content (DBD + RE are my jam!), and all things Nyxia. Stick around — there\'s always something sparkly happening!</p>',
        },
      },
      {
        id: uid(),
        label: 'Links',
        type: 'links',
        visible: true,
        content: {
          heading: 'Quick Links',
          subtitle: 'Everything you need, one tap away.',
          links: [
            { id: uid(), title: 'TikTok', description: '@nekirabelle — clips & vibes', url: 'https://www.tiktok.com/@nekirabelle', icon: '🎵' },
            { id: uid(), title: 'YouTube', description: 'Long-form content & streams', url: 'https://www.youtube.com/@nekirabelle', icon: '▶️' },
            { id: uid(), title: 'Discord', description: 'Chat with me — zsukiii', url: 'https://discord.gg/nyxia', icon: '💬' },
            { id: uid(), title: 'Nyxia Website', description: 'HWID Spoofers, Unlockers & More', url: 'https://nyxia.cc/', icon: '🛡️' },
          ],
        },
      },
      {
        id: uid(),
        label: 'Promotions',
        type: 'promotions',
        visible: true,
        content: {
          heading: 'Promo Spotlight',
          subtitle: 'Featured partners & products I love.',
        },
      },
      {
        id: uid(),
        label: 'Guestbook',
        type: 'comments',
        visible: true,
        content: {
          heading: 'Leave a message',
          subtitle: 'Say hi — comments update live! ✨',
        },
      },
    ],
    comments: {
      enabled: true,
      placeholder: 'Write something sweet...',
      namePlaceholder: 'Your name',
      maxLength: 500,
      badgeTemplates: [
        { id: uid(), label: 'VIP', icon: '💜', gradientFrom: '#c4a0ff', gradientTo: '#f0a8d0' },
        { id: uid(), label: 'Regular', icon: '⭐', gradientFrom: '#9b7bdb', gradientTo: '#e8b4f8' },
        { id: uid(), label: 'OG', icon: '👑', gradientFrom: '#d4a88c', gradientTo: '#f0a8d0' },
      ],
    },
    promotions: [
      {
        id: uid(),
        title: 'Nyxia.cc',
        description: 'HWID Spoofers, Game Unlockers & more — stay ahead of the curve with Nyxia\'s latest products. Stay unlocked + protected!',
        image: '',
        url: 'https://nyxia.cc/',
        buttonText: 'Visit Nyxia',
        accentColor: '#c4a0ff',
        badge: 'FEATURED',
        badgeColor: '#e8b4f8',
        style: 'glow',
        visible: true,
      },
      {
        id: uid(),
        title: 'Nyxia HWID Spoofer',
        description: 'Protect your hardware identity and game with confidence. Nyxia\'s spoofer keeps you covered.',
        image: '',
        url: 'https://nyxia.cc/',
        buttonText: 'Learn More',
        accentColor: '#a78bfa',
        badge: 'NEW',
        badgeColor: '#22d3ee',
        style: 'default',
        visible: true,
      },
      {
        id: uid(),
        title: 'Nyxia Unlocker',
        description: 'Unlock premium game features and stay competitive. Built for elite gamers who demand the best.',
        image: '',
        url: 'https://nyxia.cc/',
        buttonText: 'Get Started',
        accentColor: '#f0a8d0',
        badge: 'LIVE',
        badgeColor: '#ff65ff',
        style: 'default',
        visible: true,
      },
      {
        id: uid(),
        title: 'Join Nyxia Discord',
        description: 'Connect with the community, get support, and stay updated on the latest drops.',
        image: '',
        url: 'https://discord.gg/nyxia',
        buttonText: 'Join Server',
        accentColor: '#5865F2',
        badge: '',
        badgeColor: '',
        style: 'default',
        visible: true,
      },
    ],
    music: {
      position: 'bottom-right',
      style: 'expanded',
      autoplay: false,
      loop: true,
      shuffle: false,
      tracks: [
        {
          id: uid(),
          title: 'Everlong',
          artist: 'Foo Fighters',
          src: 'Foo Fighters - Everlong (Lyrics).mp3',
          cover: '',
        },
      ],
    },
    gallery: [],
  };
}

export function deepClone(obj) {
  return JSON.parse(JSON.stringify(obj));
}
